In [2]:
import pandas as pd
import os 
s = os.path.sep
df = pd.read_csv('c:' + s + 'Users' + s + 'titanic.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\titanic.csv'

In [3]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [3]:
df.fillna(0, axis = 0)

NameError: name 'df' is not defined

In [6]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
df.fillna(0, axis = 1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,0,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,0,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,0,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,0,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,0.0,1,2,W./C. 6607,23.4500,0,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,0,Q

In [8]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [18]:
df.dropna(axis = 1 , inplace = True)

In [19]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [16]:
print(len(df[df['Age'] == 30]))
df['Age'].fillna(30, inplace = True)
print(len(df[df['Embarked'] == "NaN"]))

23
0

In [11]:
len(df[df['Age'] == 30])

202

In [12]:
len(df[df['Embarked'] == "NaN"])

0

In [13]:
df.loc[df["Age"] == 30, ['Survived']] = 100

In [14]:
df[df["Age"] == 30]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,100,3,"Moran, Mr. James",male,30.0,0,0,330877,8.4583,NaN,Q
17,18,100,2,"Williams, Mr. Charles Eugene",male,30.0,0,0,244373,13.0000,NaN,S
19,20,100,3,"Masselmani, Mrs. Fatima",female,30.0,0,0,2649,7.2250,NaN,C
26,27,100,3,"Emir, Mr. Farred Chehab",male,30.0,0,0,2631,7.2250,NaN,C
28,29,100,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,30.0,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,100,3,"Razi, Mr. Raihed",male,30.0,0,0,2629,7.2292,NaN,C
863,864,100,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,30.0,8,2,CA. 2343,69.5500,NaN,S
868,869,100,3,"van Melkebeke, Mr. Philemon",male,30.0,0,0,345777,9.5000,NaN,S
878,879,100,3,"Laleff, Mr. Kristo",male,30.0,0,0,349217,7.8958,NaN,S
888,889,100,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,30.0,1,2,W./C. 6607,23.4500,NaN,S

In [22]:
bin(2)

'0b10'

In [24]:
bin(4)

'0b100'

In [27]:
print('{0:b}'.format(int('2')))

10

In [28]:
int('1010',2)

10

In [31]:
import numpy as np
print(np.log(20))

2.995732273553991

In [35]:
help(np.log(2))

Help on float64 object:

class float64(floating, builtins.float)
 |  float64(x=0, /)
 |
 |  Double-precision floating-point number type, compatible with Python `float`
 |  and C ``double``.
 |  Character code: ``'d'``.
 |  Canonical name: ``np.double``.
 |  Alias: ``np.float_``.
 |  Alias *on this platform*: ``np.float64``: 64-bit precision floating-point number type: sign bit, 11 bits exponent, 52 bits mantissa.
 |
 |  Method resolution order:
 |      float64
 |      floating
 |      inexact
 |      number
 |      generic
 |      builtins.float
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __abs__(self, /)
 |      abs(self)
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __bool__(self, /)
 |      self != 0
 |
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __float__(self, /)
 |      float(self)
 |
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __hash__(self, /)
 |      Return hash(self).
 |
 |  __int__(self, /)
 |      int(self)
 |
 |  __le__(self, value, /)
 |      Return self<=value.
 |
 |  __lt__(self, value, /)
 |      Return self<value.
 |
 |  __mod__(self, value, /)
 |      Return self%value.
 |
 |  __mul__(self, value, /)
 |      Return self*value.
 |
 |  __ne__(self, value, /)
 |      Return self!=value.
 |
 |  __neg__(self, /)
 |      -self
 |
 |  __pos__(self, /)
 |      +self
 |
 |  __pow__(self, value, mod=None, /)
 |      Return pow(self, value, mod).
 |
 |  __radd__(self, value, /)
 |      Return value+self.
 |
 |  __rdivmod__(self, value, /)
 |      Return divmod(value, self).
 |
 |  __repr__(self, /)
 |      Return repr(self).
 |
 |  __rfloordiv__(self, value, /)
 |      Return value//self.
 |
 |  __rmod__(self, value, /)
 |      Return value%self.
 |
 |  __rmul__(self, value, /)
 |      Return value*self.
 |
 |  __rpow__(self, value, mod=None, /)
 |      Return pow(value, self, mod).
 |
 |  __rsub__(self, value, /)
 |      Return value-self.
 |
 |  __rtruediv__(self, value, /)
 |      Return value/self.
 |
 |  __str__(self, /)
 |      Return str(self).
 |
 |  __sub__(self, value, /)
 |      Return self-value.
 |
 |  __truediv__(self, value, /)
 |      Return self/value.
 |
 |  as_integer_ratio(...)
 |      double.as_integer_ratio() -> (int, int)
 |
 |      Return a pair of integers, whose ratio is exactly equal to the original
 |      floating point number, and with a positive denominator.
 |      Raise OverflowError on infinities and a ValueError on NaNs.
 |
 |      >>> np.double(10.0).as_integer_ratio()
 |      (10, 1)
 |      >>> np.double(0.0).as_integer_ratio()
 |      (0, 1)
 |      >>> np.double(-.25).as_integer_ratio()
 |      (-1, 4)
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from floating:
 |
 |  __round__(...)
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from generic:
 |
 |  __and__(self, value, /)
 |      Return self&value.
 |
 |  __array__(...)
 |      sc.__array__(dtype) return 0-dim array from scalar with specified dtype
 |
 |  __array_wrap__(...)
 |      sc.__array_wrap__(obj) return scalar from array
 |
 |  __copy__(...)
 |
 |  __deepcopy__(...)
 |
 |  __format__(...)
 |      NumPy array scalar formatter
 |
 |  __getitem__(self, key, /)
 |      Return self[key].
 |
 |  __invert__(self, /)
 |      ~self
 |
 |  __lshift__(self, value, /)
 |      Return self<<value.
 |
 |  __or__(self, value, /)
 |      Return self|value.
 |
 |  __rand__(self, value, /)
 |      Return value&self.
 |
 |  __reduce__(...)
 |      Helper for pickle.
 |
 |  __rlshift__(self, value, /)
 |      Return value<<self.
 |
 |  __ror__(self, value, /)
 |      Return value|self.
 |
 |  __rrshift__(self, value, /)
 |      Return value>>self.
 |
 |  __rshift__(self, value, /)
 |      Return self>>value.
 |
 |  __rxor__(self, value, /)
 |      Return value^self.
 |
 |  __setstate__(...)
 |
 |  __sizeof__(...)
 |      Size of object in memory, in bytes.
 |
 |  __xor__(self, value, /)
 |      Return self^value.
 |
 |  all(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  any(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  argmax(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  argmin(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  argsort(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  astype(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  byteswap(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class so as to
 |      provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  choose(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  clip(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  compress(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  conj(...)
 |
 |  conjugate(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  copy(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  cumprod(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  cumsum(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  diagonal(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  dump(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  dumps(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  fill(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  flatten(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  getfield(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  item(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  itemset(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  max(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  mean(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  min(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  newbyteorder(...)
 |      newbyteorder(new_order='S')
 |
 |      Return a new `dtype` with a different byte order.
 |
 |      Changes are also made in all fields and sub-arrays of the data type.
 |
 |      The `new_order` code can be any from the following:
 |
 |      * 'S' - swap dtype from current to opposite endian
 |      * {'<', 'L'} - little endian
 |      * {'>', 'B'} - big endian
 |      * {'=', 'N'} - native order
 |      * {'|', 'I'} - ignore (no change to byte order)
 |
 |      Parameters
 |      ----------
 |      new_order : str, optional
 |          Byte order to force; a value from the byte order specifications
 |          above.  The default value ('S') results in swapping the current
 |          byte order. The code does a case-insensitive check on the first
 |          letter of `new_order` for the alternatives above.  For example,
 |          any of 'B' or 'b' or 'biggish' are valid to specify big-endian.
 |
 |
 |      Returns
 |      -------
 |      new_dtype : dtype
 |          New `dtype` object with the given change to the byte order.
 |
 |  nonzero(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  prod(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  ptp(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  put(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  ravel(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  repeat(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  reshape(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  resize(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  round(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  searchsorted(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  setfield(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  setflags(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class so as to
 |      provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  sort(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  squeeze(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  std(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  sum(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  swapaxes(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,
 |      albeit unimplemented, all the attributes of the ndarray class
 |      so as to provide a uniform API.
 |
 |      See also the corresponding attribute of the derived class of interest.
 |
 |  take(...)
 |      Not implemented (virtual attribute)
 |
 |      Class generic exists solely to derive numpy scalars from, and possesses,

In [43]:
import math
print(math.log(2))

0.6931471805599453