In [2]:
import pandas as pd
import os
s = os.path.sep
df = pd.read_csv('c:' + s + 'Users' + s + 'linear.csv')
df

FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\linear.csv'

In [1]:
df = pd.get_dummies(df)

NameError: name 'pd' is not defined

In [83]:
train = df[:7999]
test = df[8000:]

In [84]:
x_train = train.drop('Item_Outlet_Sales', axis = 1)
x_train.head()#only has independant variables

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Identifier_DRA12,Item_Identifier_DRA24,Item_Identifier_DRA59,Item_Identifier_DRB01,Item_Identifier_DRB13,Item_Identifier_DRB24,...,Outlet_Size_High,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 1,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Grocery Store,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
0,9.30,0.016047,249.8092,1999,0,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
1,5.92,0.019278,48.2692,2009,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
2,17.50,0.016760,141.6180,1999,0,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
3,19.20,0.000000,182.0950,1998,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
4,8.93,0.000000,53.8614,1987,0,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0

In [85]:
y_train = train['Item_Outlet_Sales']
y_train.head()#shouls only have target variable

0    3735.1380
1     443.4228
2    2097.2700
3     732.3800
4     994.7052
Name: Item_Outlet_Sales, dtype: float64

In [86]:
x_test = test.drop('Item_Outlet_Sales', axis = 1)

In [101]:
y_test = test['Item_Outlet_Sales']
y_test

8000    4454.2020
8001    4233.1564
8002    5033.4480
8003    1342.2528
8004    2446.1492
          ...
8518    2778.3834
8519     549.2850
8520    1193.1136
8521    1845.5976
8522     765.6700
Name: Item_Outlet_Sales, Length: 523, dtype: float64

In [88]:
from sklearn.linear_model import LinearRegression
lg = LinearRegression()
lg

LinearRegression()

In [89]:
x_train = pd.get_dummies(x_train)
x_train

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Identifier_DRA12,Item_Identifier_DRA24,Item_Identifier_DRA59,Item_Identifier_DRB01,Item_Identifier_DRB13,Item_Identifier_DRB24,...,Outlet_Size_High,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 1,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Grocery Store,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
0,9.30,0.016047,249.8092,1999,0,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
1,5.92,0.019278,48.2692,2009,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
2,17.50,0.016760,141.6180,1999,0,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
3,19.20,0.000000,182.0950,1998,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
4,8.93,0.000000,53.8614,1987,0,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7994,10.50,0.027276,171.3106,1997,0,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0
7995,12.85,0.152748,252.0382,2009,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
7996,NaN,0.060707,127.5020,1985,0,0,0,0,0,0,...,0,0,1,1,0,0,1,0,0,0
7997,6.36,0.120788,45.7060,2002,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
7998,NaN,0.076852,111.8570,1985,0,0,0,0,0,0,...,0,0,1,1,0,0,1,0,0,0

In [90]:
x_test = pd.get_dummies(x_test)
x_test

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Identifier_DRA12,Item_Identifier_DRA24,Item_Identifier_DRA59,Item_Identifier_DRB01,Item_Identifier_DRB13,Item_Identifier_DRB24,...,Outlet_Size_High,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 1,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Grocery Store,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
8000,7.020,0.081329,150.0734,2002,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
8001,7.420,0.020388,247.1092,2004,0,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
8002,17.250,0.113518,253.5724,1997,0,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0
8003,18.750,0.052917,190.6504,2002,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
8004,20.250,0.018911,220.5772,2007,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,6.865,0.056783,214.5218,1987,0,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0
8519,8.380,0.046982,108.1570,2002,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
8520,10.600,0.035186,85.1224,2004,0,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
8521,7.210,0.145221,103.1332,2009,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
8522,14.800,0.044878,75.4670,1997,0,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0

In [92]:
x_test.fillna(0,inplace = True )

In [91]:
x_train.fillna(0, inplace = True)

In [93]:
print(lg.fit(x_train, y_train))

LinearRegression()

In [103]:
pred = lg.predict(x_test)
#pred
p = lg.predict(x_train)

In [105]:
lg.score(x_train, y_train)#r-squared

0.6497735631845378

In [96]:
lg.score(x_test, y_test)

0.40227153690776773

In [97]:
import numpy as np
rmse_test = np.sqrt(np.mean(np.power(np.array(pred) - np.array(y_test), 2)))

In [98]:
rmse_test

1255.3981735645664

In [100]:
rmse_train = np.sqrt(np.mean(np.power(np.array(lg.predict(x_train)) - np.array(y_train), 2)))

In [99]:
rmse_train

1013.0040784390595